Fix exception in ConsoleRender when property has been removed (#7)
`ConsoleRender` failed to resolve component schemas which had been removed in the "new" OpenAPI specification and threw an `IllegalArgumentException`:

```
Unexpected exception. Reason: ref '#/components/schemas/RemovedSchema' doesn't exist.

java.lang.IllegalArgumentException: ref '#/components/schemas/PermissionSet' doesn't exist.
	at com.qdesrame.openapi.diff.core.utils.RefPointer.resolveRef(RefPointer.java:20)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.resolve(ConsoleRender.java:231)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.lambda$properties$1(ConsoleRender.java:217)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.properties(ConsoleRender.java:216)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.incompatibilities(ConsoleRender.java:199)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.lambda$incompatibilities$0(ConsoleRender.java:202)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.incompatibilities(ConsoleRender.java:202)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.incompatibilities(ConsoleRender.java:185)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.itemContent(ConsoleRender.java:179)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.ul_content(ConsoleRender.java:155)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.ol_changed(ConsoleRender.java:87)
	at com.qdesrame.openapi.diff.core.output.ConsoleRender.render(ConsoleRender.java:47)
	at com.qdesrame.openapi.diff.cli.Main.main(Main.java:159)
```